### ISSUE TITLE
Create model course

### ISSUE THREAD

**Issue by clarkngo** [clarkngo/curriculum#18]
- [x] created model `course` with the following:
string - name
text - description

**Comment by conradwt** [comment]
This isn't a user-story but a task of a user-story.  For example,

As a user, I can create a course.

- [ ] create the course routes
- [ ] create the course controller
- [ ] create the course model
- [ ]  create the course migration
- [ ]  create the course views

Note:  The above should only support building the course creation.

**Comment by clarkngo** [comment]
Got it. I'll close this. Please refer to Issue - #14
